# CONSTANTS
# Nagios GROUP command ID's
GROUP_ENABLE_HOSTS_NOTIFICATIONS = 65
GROUP_DISABLE_HOSTS_NOTIFICATIONS = 66
GROUP_ENABLE_SERVICES_NOTIFICATIONS = 63
GROUP_DISABLE_SERVICES_NOTIFICATIONS = 64
GROUP_ENABLE_SERVICES_CHECKS = 67
GROUP_DISABLE_SERVICES_CHECKS = 68
# Nagios HOST command ID's
HOST_ENABLE_NOTIFICATIONS = 24
HOST_DISABLE_NOTIFICATIONS = 25
HOST_ENABLE_SERVICES_NOTIFICATIONS = 28
HOST_DISABLE_SERVICES_NOTIFICATIONS = 29
HOST_ENABLE_SERVICES_CHECKS = 15
HOST_DISABLE_SERVICES_CHECKS = 16

